require('dotenv').config();
const { 
    Client, GatewayIntentBits, SlashCommandBuilder, EmbedBuilder, 
    AttachmentBuilder, REST, Routes, PermissionFlagsBits
} = require('discord.js');
const axios = require('axios');
const mongoose = require('mongoose');
const express = require('express');

// --- RENDER.COM ÉLETBEN TARTÁS ---
const app = express();
app.get('/', (req, res) => res.send('SteamTools Master Bot is online!'));
app.listen(process.env.PORT || 3000);

// --- MONGODB ADATMODELL ---
mongoose.connect(process.env.MONGODB_URI);
const Settings = mongoose.model('Settings', new mongoose.Schema({
    allowedUsers: [String],
    allowedChannels: [String]
}));

// --- FORRÁSOK AZ LTSTEAMPLUGIN ALAPJÁN ---
const MANIFEST_SOURCES = [
    { name: 'LuaTools Bypasses', url: (id) => `https://files.luatools.work/GameBypasses/${id}.zip` },
    { name: 'Ryuu Server', url: (id) => `http://167.235.229.108/${id}` },
    { name: 'Sushi Repo', url: (id) => `https://raw.githubusercontent.com/sushi-dev55-alt/sushitools-games-repo-alt/refs/heads/main/${id}.zip` },
    { name: 'TwentyTwo Cloud', url: (id) => `http://masss.pythonanywhere.com/storage?auth=IEOIJE54esfsipoE56GE4&appid=${id}` },
    { name: 'ManifestHub', url: (id) => `https://codeload.github.com/SteamAutoCracks/ManifestHub/zip/refs/heads/${id}` }
];

const ONLINE_FIX_SOURCE = "https://files.luatools.work/OnlineFix1/";

const client = new Client({ 
    intents: [
        GatewayIntentBits.Guilds, 
        GatewayIntentBits.GuildMessages, 
        GatewayIntentBits.MessageContent 
    ] 
});

// --- SEGÉDFÜGGVÉNYEK ---

async function fetchFromSources(id) {
    for (const source of MANIFEST_SOURCES) {
        try {
            const res = await axios({ method: 'get', url: source.url(id), responseType: 'arraybuffer', timeout: 5000 });
            if (res.status === 200) return { data: res.data, source: source.name };
        } catch (e) { continue; }
    }
    return null;
}

async function processToLua(attachments, appId = "unknown") {
    let manifestFiles = {};
    let configData = {};
    for (const a of attachments.values()) {
        const res = await axios.get(a.url, { responseType: 'text' }).catch(() => null);
        if (!res) continue;
        if (a.name.endsWith('.manifest')) {
            const parts = a.name.split('_');
            if (parts.length >= 2) manifestFiles[parts[0]] = parts[1].replace('.manifest', '');
        } else if (a.name === 'config.vdf') {
            const match = res.data.matchAll(/"(\d+)"\s*{\s*"DecryptionKey"\s*"([^"]+)"/g);
            for (const m of match) configData[m[1]] = m[2];
        }
    }
    let lua = `-- Generated by Master Bot (Manilua)\naddappid(${appId})\n`;
    for (const id in manifestFiles) {
        if (configData[id]) lua += `addappid(${id}, 1, "${configData[id]}")\n`;
        lua += `setManifestid(${id}, "${manifestFiles[id]}", 0)\n`;
    }
    return lua;
}

// --- SLASH PARANCSOK REGISZTRÁLÁSA (JAVÍTVA) ---
const commands = [
    new SlashCommandBuilder()
        .setName('manifest')
        .setDescription('Manifest és .lua feloldó letöltése')
        .addStringOption(o => o.setName('query').setDescription('Játék név vagy ID').setRequired(true).setAutocomplete(true))
        .addBooleanOption(o => o.setName('dlc').setDescription('Összes DLC feloldása a .lua fájlban?').setRequired(false)),
    
    new SlashCommandBuilder()
        .setName('onlinefix')
        .setDescription('Online-Fix (.zip) letöltése a LuaTools szerveréről')
        .addStringOption(o => o.setName('query').setDescription('Játék név vagy ID').setRequired(true).setAutocomplete(true)),

    new SlashCommandBuilder()
        .setName('fix')
        .setDescription('Steam indítási hiba javítása (appinfo.vdf)'),

    new SlashCommandBuilder()
        .setName('manage')
        .setDescription('Admin beállítások')
        .setDefaultMemberPermissions(PermissionFlagsBits.Administrator)
        .addSubcommand(s => 
            s.setName('user')
            .setDescription('Felhasználó engedélyezése')
            .addUserOption(o => o.setName('target').setDescription('A választott felhasználó').setRequired(true)))
        .addSubcommand(s => 
            s.setName('channel')
            .setDescription('Csatorna engedélyezése')
            .addChannelOption(o => o.setName('target').setDescription('A választott csatorna').setRequired(true)))
].map(c => c.toJSON());

// --- ESEMÉNYEK ---

client.once('ready', async () => {
    const rest = new REST({ version: '10' }).setToken(process.env.DISCORD_TOKEN);
    try {
        await rest.put(Routes.applicationCommands(client.user.id), { body: commands });
        console.log(`✅ ${client.user.tag} online - LuaTools források beépítve!`);
    } catch (e) {
        console.error('Hiba a parancsok regisztrálásakor:', e);
    }
});

client.on('interactionCreate', async interaction => {
    if (interaction.isAutocomplete()) {
        const focused = interaction.options.getFocused();
        const url = `https://store.steampowered.com/api/storesearch/?term=${encodeURIComponent(focused)}&l=hungarian&cc=HU`;
        const res = await axios.get(url).catch(() => ({ data: { items: [] } }));
        const suggestions = res.data.items.map(g => ({ name: `${g.name.substring(0, 80)} (${g.id})`, value: g.id.toString() })).slice(0, 20);
        await interaction.respond(suggestions);
    }

    if (!interaction.isChatInputCommand()) return;
    let db = await Settings.findOne() || await Settings.create({ allowedUsers: [process.env.ADMIN_ID], allowedChannels: [] });

    // --- ONLINE-FIX LETÖLTÉS ---
    if (interaction.commandName === 'onlinefix') {
        const appId = interaction.options.getString('query');
        await interaction.deferReply({ ephemeral: true });
        try {
            const url = `${ONLINE_FIX_SOURCE}${appId}.zip`;
            const res = await axios({ method: 'get', url: url, responseType: 'arraybuffer' }).catch(() => null);
            if (res && res.status === 200) {
                const file = new AttachmentBuilder(Buffer.from(res.data), { name: `OnlineFix_${appId}.zip` });
                await interaction.editReply({ content: `✅ **Online-Fix** letöltve a LuaTools szerveréről!`, files: [file] });
            } else {
                await interaction.editReply("❌ Ehhez a játékhoz nincs Online-Fix a LuaTools adatbázisában.");
            }
        } catch (e) { await interaction.editReply("❌ Hiba történt."); }
    }

    // --- MANIFEST ÉS LUA KERESÉS ---
    if (interaction.commandName === 'manifest') {
        const appId = interaction.options.getString('query');
        const includeDlc = interaction.options.getBoolean('dlc') ?? true;
        await interaction.deferReply({ ephemeral: true });

        try {
            const steamRes = await axios.get(`https://store.steampowered.com/api/appdetails?appids=${appId}`);
            if (!steamRes.data[appId].success) return interaction.editReply("❌ Hiba a Steam adatok lekérésekor.");
            
            const gameData = steamRes.data[appId].data;
            const dlcs = gameData.dlc || [];

            let lua = `-- SteamTools Unlocker\naddappid(${appId})\n`;
            if (includeDlc) dlcs.forEach(id => lua += `addappid(${id})\n`);
            const luaFile = new AttachmentBuilder(Buffer.from(lua), { name: `unlock_${appId}.lua` });

            const manifest = await fetchFromSources(appId);
            let files = [luaFile];
            let status = [`✅ **${gameData.name}** feloldó (.lua) elkészült.`];

            if (manifest) {
                files.push(new AttachmentBuilder(Buffer.from(manifest.data), { name: `manifest_${appId}.zip` }));
                status.push(`✅ Manifest ZIP megtalálva: [${manifest.source}]`);
            }

            const embed = new EmbedBuilder()
                .setTitle(`📦 Csomag: ${gameData.name}`)
                .setColor(0x00FF00)
                .setDescription(status.join('\n') + `\n🔹 **DLC-k száma:** ${dlcs.length}`);

            await interaction.editReply({ embeds: [embed], files: files });
        } catch (e) { await interaction.editReply("❌ Hiba történt a generálás során."); }
    }

    // FIX PARANCS
    if (interaction.commandName === 'fix') {
        return interaction.reply({ content: "🛠️ **Steam hiba javítása:** Töröld az `appinfo.vdf` fájlt a `Steam/appcache` mappából!", ephemeral: true });
    }

    // ADMIN RÉSZ (MANAGE)
    if (interaction.commandName === 'manage') {
        if (interaction.user.id !== process.env.ADMIN_ID) return interaction.reply({ content: '❌ Csak az admin!', ephemeral: true });
        const sub = interaction.options.getSubcommand();
        const target = interaction.options.getMember('target') || interaction.options.getChannel('target');
        
        if (sub === 'user') {
            if (!db.allowedUsers.includes(target.id)) db.allowedUsers.push(target.id);
        } else if (sub === 'channel') {
            if (!db.allowedChannels.includes(target.id)) db.allowedChannels.push(target.id);
        }
        await db.save();
        return interaction.reply({ content: '✅ Beállítások elmentve!', ephemeral: true });
    }
});

// Manuális fájl bedobás (Manilua)
client.on('messageCreate', async message => {
    if (message.author.bot || message.attachments.size === 0) return;
    const hasFiles = message.attachments.some(a => a.name.endsWith('.manifest') || a.name === 'config.vdf');
    if (hasFiles) {
        const lua = await processToLua(message.attachments);
        if (lua) {
            const file = new AttachmentBuilder(Buffer.from(lua), { name: 'generated_unlock.lua' });
            message.reply({ content: "✅ Észleltem a fájlokat! Itt a generált feloldó:", files: [file] });
        }
    }
});

client.login(process.env.DISCORD_TOKEN);
