require('dotenv').config();
const { 
    Client, GatewayIntentBits, SlashCommandBuilder, EmbedBuilder, 
    AttachmentBuilder, REST, Routes, PermissionFlagsBits
} = require('discord.js');
const axios = require('axios');
const mongoose = require('mongoose');
const express = require('express');

// --- RENDER ÉLETBEN TARTÁS ---
const app = express();
app.get('/', (req, res) => res.send('SteamTools Bot is Active!'));
app.listen(process.env.PORT || 3000);

// --- ADATBÁZIS ---
mongoose.connect(process.env.MONGODB_URI).catch(err => console.error("MongoDB hiba:", err));
const Settings = mongoose.model('Settings', new mongoose.Schema({
    allowedUsers: [String],
    allowedChannels: [String]
}));

// --- MANIFEST FORRÁSOK (ltsteamplugin alapján) ---
const MANIFEST_SOURCES = [
    { name: 'Morrenus', url: (id) => `https://manifest.morrenus.xyz/api/v1/manifest/${id}?api_key=${process.env.MORRENUS_API_KEY}` },
    { name: 'Ryuu', url: (id) => `http://167.235.229.108/${id}` },
    { name: 'TwentyTwo', url: (id) => `http://masss.pythonanywhere.com/storage?auth=IEOIJE54esfsipoE56GE4&appid=${id}` },
    { name: 'Sushi', url: (id) => `https://raw.githubusercontent.com/sushi-dev55-alt/sushitools-games-repo-alt/refs/heads/main/${id}.zip` },
    { name: 'ManifestHub', url: (id) => `https://codeload.github.com/SteamAutoCracks/ManifestHub/zip/refs/heads/${id}` }
];

const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages] });

// --- KERESÉS JAVÍTÁSA ---
async function findGameInfo(input) {
    try {
        // 1. Ha szám, akkor ez egy AppID
        if (!isNaN(input) && input.trim() !== "") {
            return { id: input.trim(), searchName: input };
        }

        // 2. Ha szöveg, megkeressük a Steam áruházban
        const searchUrl = `https://store.steampowered.com/api/storesearch/?term=${encodeURIComponent(input)}&l=hungarian&cc=HU`;
        const res = await axios.get(searchUrl);

        if (res.data && res.data.items && res.data.items.length > 0) {
            return { 
                id: res.data.items[0].id.toString(), 
                name: res.data.items[0].name 
            };
        }
    } catch (e) {
        console.error("Keresési hiba:", e.message);
    }
    return null;
}

async function getManifest(id) {
    for (const source of MANIFEST_SOURCES) {
        try {
            const res = await axios.get(source.url(id), { responseType: 'arraybuffer', timeout: 5000 });
            if (res.status === 200) return { data: res.data, source: source.name };
        } catch (e) { continue; }
    }
    return null;
}

client.on('interactionCreate', async interaction => {
    if (!interaction.isChatInputCommand()) return;

    // Jogosultság szűrés
    const settings = await Settings.findOne();
    const isAdmin = interaction.member.permissions.has(PermissionFlagsBits.Administrator);
    if (!isAdmin && !settings?.allowedUsers?.includes(interaction.user.id) && !settings?.allowedChannels?.includes(interaction.channelId)) {
        return interaction.reply({ content: "❌ Nincs jogosultságod a bot használatához!", ephemeral: true });
    }

    if (interaction.commandName === 'manifest') {
        await interaction.deferReply({ ephemeral: true });

        const query = interaction.options.getString('appid');
        const game = await findGameInfo(query);

        if (!game) {
            return interaction.editReply(`❌ Nem találtam ilyen nevű játékot: **${query}**`);
        }

        try {
            const steamRes = await axios.get(`https://store.steampowered.com/api/appdetails?appids=${game.id}&l=hungarian`);
            const appData = steamRes.data[game.id];

            if (!appData || !appData.success) {
                return interaction.editReply(`❌ A Steam nem küldött adatokat az azonosítóhoz: ${game.id}`);
            }

            const details = appData.data;
            const dlcs = details.dlc || [];
            const includeDlc = interaction.options.getBoolean('dlc') !== false;

            // LUA Generálás
            let lua = `-- Generated by SteamTools Master\n-- Game: ${details.name}\nadd_app(${game.id})\n`;
            if (includeDlc) dlcs.forEach(id => lua += `add_app(${id})\n`);

            const manifest = await getManifest(game.id);

            const embed = new EmbedBuilder()
                .setTitle(`📦 ${details.name}`)
                .setColor(0x00FF00)
                .setThumbnail(details.header_image)
                .addFields(
                    { name: 'AppID', value: game.id, inline: true },
                    { name: 'DLC-k száma', value: dlcs.length.toString(), inline: true },
                    { name: 'Manifest ZIP', value: manifest ? `✅ (${manifest.source})` : '❌ Nem található', inline: true }
                )
                .setFooter({ text: "Húzd a .lua fájlt a SteamTools-ra a telepítéshez!" });

            const files = [new AttachmentBuilder(Buffer.from(lua), { name: `unlock_${game.id}.lua` })];
            if (manifest) files.push(new AttachmentBuilder(Buffer.from(manifest.data), { name: `manifest_${game.id}.zip` }));

            await interaction.editReply({ embeds: [embed], files: files });

        } catch (err) {
            console.error(err);
            await interaction.editReply("❌ Hiba történt a fájlok előkészítésekor.");
        }
    }
});

// --- PARANCS REGISZTRÁCIÓ (Automatikus) ---
const rest = new REST({ version: '10' }).setToken(process.env.DISCORD_TOKEN);
(async () => {
    try {
        const commands = [
            new SlashCommandBuilder()
                .setName('manifest')
                .setDescription('Manifest kereső és LUA generáló')
                .addStringOption(o => o.setName('appid').setDescription('Játék neve vagy AppID-ja').setRequired(true))
                .addBooleanOption(o => o.setName('dlc').setDescription('DLC-k feloldása? (Alapértelmezett: True)'))
        ].map(c => c.toJSON());

        await rest.put(Routes.applicationCommands(process.env.CLIENT_ID), { body: commands });
        console.log('✅ Parancsok sikeresen frissítve!');
    } catch (e) { console.error("❌ Regisztrációs hiba:", e); }
})();

client.login(process.env.DISCORD_TOKEN);
